import { useState, useEffect } from 'react';
import { Button } from './ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from './ui/dialog';
import { Input } from './ui/input';
import { Course, CourseColor, GradeConfigItem, SubjectCategory } from '../types';
import GradePeriodsFields from './GradePeriodsFields';
import { useLanguage } from '../contexts/LanguageContext';
import { COURSE_COLORS } from '../lib/constants';
import { getColorValue } from '../lib/courseUtils';
import { getApplicableGrades } from '../lib/courseGradeUtils';

interface EditCourseDialogProps {
  course: Course | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSave: (
    courseId: string,
    updates: {
      name: string;
      subjectCategory: SubjectCategory;
      applicableGrades: string[];
      weeklyPeriodsByGrade: Record<string, number>;
      textbookVersion?: string;
      color: CourseColor;
    },
  ) => void;
  gradeItems: GradeConfigItem[];
}

export default function EditCourseDialog({
  course,
  open,
  onOpenChange,
  onSave,
  gradeItems,
}: EditCourseDialogProps) {
  const { t, language } = useLanguage();
  const [subjectCategoryZh, setSubjectCategoryZh] = useState('');
  const [subjectCategoryEn, setSubjectCategoryEn] = useState('');
  const [applicableGrades, setApplicableGrades] = useState<string[]>([]);
  const [weeklyPeriodsByGrade, setWeeklyPeriodsByGrade] = useState<Record<string, number>>({});
  const [textbookVersion, setTextbookVersion] = useState('人教版');
  const [selectedColor, setSelectedColor] = useState<CourseColor>('light-blue');

  useEffect(() => {
    if (course) {
      if (typeof course.subjectCategory === 'object' && 'zh' in course.subjectCategory && 'en' in course.subjectCategory) {
        setSubjectCategoryZh(course.subjectCategory.zh);
        setSubjectCategoryEn(course.subjectCategory.en);
      } else {
        const oldCategory = course.subjectCategory || course.name;
        setSubjectCategoryZh(oldCategory as string);
        setSubjectCategoryEn(oldCategory as string);
      }
      setApplicableGrades(getApplicableGrades(course));
      setWeeklyPeriodsByGrade({ ...(course.weeklyPeriodsByGrade || {}) });
      setTextbookVersion(course.textbookVersion || '人教版');
      setSelectedColor(course.color);
    }
  }, [course]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (
      course &&
      subjectCategoryZh.trim() &&
      subjectCategoryEn.trim() &&
      textbookVersion.trim() &&
      applicableGrades.length > 0
    ) {
      const categoryText = language === 'zh' ? subjectCategoryZh.trim() : subjectCategoryEn.trim();
      const autoGeneratedName = `${categoryText}-${textbookVersion.trim()}`;
      const subjectCategory: SubjectCategory = {
        zh: subjectCategoryZh.trim(),
        en: subjectCategoryEn.trim(),
      };
      onSave(course.id, {
        name: autoGeneratedName,
        subjectCategory,
        applicableGrades,
        weeklyPeriodsByGrade,
        textbookVersion: textbookVersion.trim() || '人教版',
        color: selectedColor,
      });
      onOpenChange(false);
    }
  };

  const handleCancel = () => {
    onOpenChange(false);
  };

  if (!course) {
    return null;
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[90vh] flex w-full max-w-[min(40rem,calc(100vw-2rem))] flex-col overflow-hidden gap-0 p-4 sm:p-6">
        <DialogHeader className="flex-shrink-0 pr-8">
          <DialogTitle>{t('course.edit')}</DialogTitle>
          <DialogDescription>
            {t('dialog.editCourse.description')}
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="flex flex-col flex-1 min-h-0 overflow-hidden gap-0">
          <div className="py-3 space-y-3 overflow-y-auto min-h-0 flex-1 pr-1 -mr-1">
            <div>
              <label className="text-sm font-medium text-gray-700 mb-2 block">
                {language === 'zh' ? '课程名称（自动生成）' : 'Course Name (Auto-generated)'}
              </label>
              <Input
                value={subjectCategoryZh.trim() && subjectCategoryEn.trim() && textbookVersion.trim() 
                  ? `${language === 'zh' ? subjectCategoryZh.trim() : subjectCategoryEn.trim()}-${textbookVersion.trim()}` 
                  : ''}
                disabled
                className="bg-gray-50"
              />
              <p className="text-xs text-gray-500 mt-1">
                {t('hint.courseNameAuto')}
              </p>
            </div>
            <div>
              <label className="text-sm font-medium text-gray-700 mb-2 block">
                {t('course.subjectCategory')} <span className="text-red-500">*</span>
              </label>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <Input
                    placeholder={language === 'zh' ? '中文类别（如：数学）' : 'Chinese Category (e.g., 数学)'}
                    value={subjectCategoryZh}
                    onChange={(e) => setSubjectCategoryZh(e.target.value)}
                    autoFocus
                  />
                </div>
                <div>
                  <Input
                    placeholder={language === 'zh' ? '英文类别（如：Math）' : 'English Category (e.g., Math)'}
                    value={subjectCategoryEn}
                    onChange={(e) => setSubjectCategoryEn(e.target.value)}
                  />
                </div>
              </div>
              <p className="text-xs text-gray-500 mt-1">
                {language === 'zh' ? '用于分组显示，相同类别的课程会显示在同一列' : 'Used for grouping, courses with the same category will be displayed in the same column'}
              </p>
            </div>
            <div>
              <label className="text-sm font-medium text-gray-700 mb-2 block">
                {t('course.gradeRange')}
              </label>
              <GradePeriodsFields
                applicableGrades={applicableGrades}
                weeklyPeriodsByGrade={weeklyPeriodsByGrade}
                gradeItems={gradeItems}
                onChange={({ applicableGrades: ag, weeklyPeriodsByGrade: wp }) => {
                  setApplicableGrades(ag);
                  setWeeklyPeriodsByGrade(wp);
                }}
              />
              <p className="text-xs text-gray-500 mt-1">{t('hint.gradeRange')}</p>
            </div>
            <div>
              <label className="text-sm font-medium text-gray-700 mb-2 block">
                {t('course.textbookVersion')} <span className="text-red-500">*</span>
              </label>
              <Input
                value={textbookVersion}
                onChange={(e) => setTextbookVersion(e.target.value)}
                placeholder={t('hint.textbookVersion')}
              />
              <p className="text-xs text-gray-500 mt-1">
                {language === 'zh' ? '该课程使用的教材版本，用于AI生成单元时自动搜索教材信息。课程名称将自动生成为"课程类别-教材版本"' : 'Textbook version used for this course, used for AI unit generation. Course name will be auto-generated as "Subject Category-Textbook Version"'}
              </p>
            </div>
            <div>
              <label className="text-sm font-medium text-gray-700 mb-2 block">
                {t('course.color')}
              </label>
              <div className="flex gap-2 flex-wrap">
                {COURSE_COLORS.map((color) => (
                  <button
                    key={color.value}
                    type="button"
                    onClick={() => setSelectedColor(color.value)}
                    className={`w-9 h-9 rounded-md border-2 transition-all relative overflow-hidden ${
                      selectedColor === color.value
                        ? 'border-gray-800 scale-110'
                        : 'border-gray-300 hover:border-gray-400'
                    }`}
                    title={language === 'zh' ? color.label : color.labelEn}
                  >
                    <div 
                      className="absolute inset-0"
                      style={{
                        background: `linear-gradient(135deg, ${getColorValue(color.light)} 0%, ${getColorValue(color.light)} 50%, ${getColorValue(color.standard)} 50%, ${getColorValue(color.standard)} 100%)`
                      }}
                    />
                  </button>
                ))}
              </div>
            </div>
          </div>
          <DialogFooter className="flex-shrink-0 pt-3 mt-2 border-t border-slate-200 sm:mt-0">
            <Button type="button" variant="outline" onClick={handleCancel}>
              {t('common.cancel')}
            </Button>
            <Button
              type="submit"
              disabled={
                !subjectCategoryZh.trim() ||
                !subjectCategoryEn.trim() ||
                !textbookVersion.trim() ||
                applicableGrades.length === 0
              }
            >
              {t('common.save')}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
